import React, { useEffect, useState } from 'react';
import { useTranslation } from '../contexts/I18nContext';
import { settingsService } from '../services/settingsService';
import { SchoolProfile as ISchoolProfile } from '../types';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Input } from '../components/ui/input';
import { Button } from '../components/ui/button';
import { Label } from '../components/ui/label';
import { Building2 } from 'lucide-react';

export const SchoolProfile: React.FC = () => {
  const { t } = useTranslation();
  const [profile, setProfile] = useState<ISchoolProfile | null>(null);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    setLoading(true);
    settingsService.getProfile().then(data => {
      setProfile(data);
      setLoading(false);
    });
  }, []);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!profile) return;
    setSaving(true);
    await settingsService.updateProfile(profile);
    setSaving(false);
  };

  if (loading || !profile) return <div className="p-6">{t('common.loading')}</div>;

  return (
    <div className="max-w-3xl space-y-6">
      <h2 className="text-3xl font-bold tracking-tight">{t('profile.title')}</h2>

      <Card>
        <CardHeader className="flex flex-row items-center gap-4">
          <div className="p-3 bg-primary/10 rounded-full">
            <Building2 className="h-8 w-8 text-primary" />
          </div>
          <CardTitle>{t('profile.title')}</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSave} className="space-y-6">
            <div className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="name">{t('profile.school_name')}</Label>
                <Input 
                  id="name" 
                  value={profile.name} 
                  onChange={(e) => setProfile({...profile, name: e.target.value})} 
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="website">{t('profile.website')}</Label>
                  <Input 
                    id="website" 
                    value={profile.website} 
                    onChange={(e) => setProfile({...profile, website: e.target.value})} 
                  />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="email">Email</Label>
                  <Input 
                    id="email" 
                    value={profile.email} 
                    onChange={(e) => setProfile({...profile, email: e.target.value})} 
                  />
                </div>
              </div>

              <div className="grid gap-2">
                <Label htmlFor="address">{t('profile.address')}</Label>
                <Input 
                  id="address" 
                  value={profile.address} 
                  onChange={(e) => setProfile({...profile, address: e.target.value})} 
                />
              </div>

              <div className="grid gap-2">
                <Label htmlFor="did">{t('profile.issuer_did')}</Label>
                <Input 
                  id="did" 
                  value={profile.issuerDid || ''} 
                  disabled
                  className="bg-muted text-muted-foreground"
                />
                <p className="text-xs text-muted-foreground">Generated by Cardano Wallet</p>
              </div>
            </div>

            <div className="flex justify-end">
               <Button type="submit" isLoading={saving}>{t('common.save')}</Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
};